/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package csfmarksanalysismvc;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author tg
 */
public class CSFView extends javax.swing.JFrame {
    
    private boolean dMode = CSFMarksAnalysisMVC.developerMode;
    private DefaultListModel gradesArray = new DefaultListModel();
    
    public CSFView() {
        if(dMode) System.out.println("View: CSFView() Constructor");
        try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CSFView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Text file *.txt", "txt", "text");
        fileChooserTxt.setFileFilter(filter);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooserTxt = new javax.swing.JFileChooser();
        lblGrades = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listGrades = new javax.swing.JList<>();
        btnClearAll = new javax.swing.JButton();
        btnDeleteElement = new javax.swing.JButton();
        txtNewGrade = new javax.swing.JTextField();
        btnAddElement = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        cboxDefaultFile = new javax.swing.JCheckBox();
        lblFullMarksPassText = new javax.swing.JLabel();
        lblBorderLinePassText = new javax.swing.JLabel();
        lblFullPaperPassText = new javax.swing.JLabel();
        lblFailesSection1Text = new javax.swing.JLabel();
        lblFailedSection2Text = new javax.swing.JLabel();
        lblFailedSection3Text = new javax.swing.JLabel();
        lblPassText = new javax.swing.JLabel();
        lblFailText = new javax.swing.JLabel();
        btnExportReport = new javax.swing.JButton();
        lblNumberOfElementsText = new javax.swing.JLabel();
        lblNumberOfElements = new javax.swing.JLabel();
        lblFullMarksPass = new javax.swing.JLabel();
        lblBorderLinePass = new javax.swing.JLabel();
        lblFullPaperPass = new javax.swing.JLabel();
        lblFailedSection1 = new javax.swing.JLabel();
        lblFailedSection2 = new javax.swing.JLabel();
        lblFailedSection3 = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblFail = new javax.swing.JLabel();

        fileChooserTxt.setDialogTitle("");
        fileChooserTxt.setName("fileChooserTxt"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CSF Marks Analysis App");
        setLocation(new java.awt.Point(500, 250));
        setName("appFrame"); // NOI18N
        setResizable(false);

        lblGrades.setText("Grades:");
        lblGrades.setName("lblGrades"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        listGrades.setModel(gradesArray);
        listGrades.setName("listGrades"); // NOI18N
        jScrollPane1.setViewportView(listGrades);

        btnClearAll.setText("Clear all");
        btnClearAll.setName("btnClearAll"); // NOI18N

        btnDeleteElement.setText("Delete selected");
        btnDeleteElement.setName("btnDeleteElement"); // NOI18N

        txtNewGrade.setName("txtNewGrade"); // NOI18N
        txtNewGrade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewGradeFocusGained(evt);
            }
        });

        btnAddElement.setText("Add");
        btnAddElement.setName("btnAddElement"); // NOI18N

        btnExit.setText("Exit");
        btnExit.setName("btnExit"); // NOI18N

        btnImport.setText("<--- Import from file");
        btnImport.setName("btnImport"); // NOI18N

        btnExport.setText("Export to file --->");
        btnExport.setName("btnExport"); // NOI18N

        cboxDefaultFile.setSelected(true);
        cboxDefaultFile.setText("Default file");
        cboxDefaultFile.setName("cboxDefaultFile"); // NOI18N

        lblFullMarksPassText.setText("Full Marks Pass:");
        lblFullMarksPassText.setName("lblFullMarksPassText"); // NOI18N

        lblBorderLinePassText.setText("Border Line Pass:");
        lblBorderLinePassText.setName("lblBorderLinePassText"); // NOI18N

        lblFullPaperPassText.setText("Full Paper Pass:");
        lblFullPaperPassText.setName("lblFullPaperPassText"); // NOI18N

        lblFailesSection1Text.setText("Failed Section 1:");
        lblFailesSection1Text.setName("lblFailesSection1Text"); // NOI18N

        lblFailedSection2Text.setText("Failed Section 2:");
        lblFailedSection2Text.setName("lblFailedSection2Text"); // NOI18N

        lblFailedSection3Text.setText("Failed Section 3:");
        lblFailedSection3Text.setName("lblFailedSection3Text"); // NOI18N

        lblPassText.setText("PASS:");
        lblPassText.setName("lblPassText"); // NOI18N

        lblFailText.setText("FAIL:");
        lblFailText.setName("lblFailText"); // NOI18N

        btnExportReport.setText("Export Analysis to file");
        btnExportReport.setName("btnExportReport"); // NOI18N

        lblNumberOfElementsText.setText("Number of elements:");
        lblNumberOfElementsText.setName("lblNumberOfElementsText"); // NOI18N

        lblNumberOfElements.setText("0");
        lblNumberOfElements.setName("lblNumberOfElements"); // NOI18N

        lblFullMarksPass.setText("0%");
        lblFullMarksPass.setName("lblFullMarksPass"); // NOI18N

        lblBorderLinePass.setText("0%");
        lblBorderLinePass.setName("lblBorderLinePass"); // NOI18N

        lblFullPaperPass.setText("0%");
        lblFullPaperPass.setName("lblFullPaperPass"); // NOI18N

        lblFailedSection1.setText("0%");
        lblFailedSection1.setName("lblFailedSection1"); // NOI18N

        lblFailedSection2.setText("0%");
        lblFailedSection2.setName("lblFailedSection2"); // NOI18N

        lblFailedSection3.setText("0%");
        lblFailedSection3.setName("lblFailedSection3"); // NOI18N

        lblPass.setText("0%");
        lblPass.setName("lblPass"); // NOI18N

        lblFail.setText("0%");
        lblFail.setName("lblFail"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGrades)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnImport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cboxDefaultFile))
                            .addComponent(btnExportReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFailText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFail))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNumberOfElementsText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNumberOfElements))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFullMarksPassText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFullMarksPass))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBorderLinePassText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblBorderLinePass))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFullPaperPassText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFullPaperPass))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFailesSection1Text)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFailedSection1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFailedSection2Text)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFailedSection2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFailedSection3Text)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFailedSection3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPassText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPass))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnClearAll)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(btnDeleteElement))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNewGrade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddElement)))
                        .addGap(168, 168, 168))
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGrades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnImport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxDefaultFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumberOfElementsText)
                            .addComponent(lblNumberOfElements))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFullMarksPassText)
                            .addComponent(lblFullMarksPass))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBorderLinePassText)
                            .addComponent(lblBorderLinePass))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFullPaperPassText)
                            .addComponent(lblFullPaperPass))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFailesSection1Text)
                            .addComponent(lblFailedSection1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFailedSection2Text)
                            .addComponent(lblFailedSection2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFailedSection3Text)
                            .addComponent(lblFailedSection3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPassText)
                            .addComponent(lblPass))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFailText)
                            .addComponent(lblFail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExportReport))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearAll)
                    .addComponent(btnDeleteElement))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddElement))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void txtNewGradeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewGradeFocusGained
        if(dMode) System.out.println("txtNewGradeFocusGained()");
        txtNewGrade.setText("");
        txtNewGrade.setBorder(BorderFactory.createLineBorder(Color.gray));
    }//GEN-LAST:event_txtNewGradeFocusGained
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddElement;
    private javax.swing.JButton btnClearAll;
    private javax.swing.JButton btnDeleteElement;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnExportReport;
    private javax.swing.JButton btnImport;
    private javax.swing.JCheckBox cboxDefaultFile;
    private javax.swing.JFileChooser fileChooserTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBorderLinePass;
    private javax.swing.JLabel lblBorderLinePassText;
    private javax.swing.JLabel lblFail;
    private javax.swing.JLabel lblFailText;
    private javax.swing.JLabel lblFailedSection1;
    private javax.swing.JLabel lblFailedSection2;
    private javax.swing.JLabel lblFailedSection2Text;
    private javax.swing.JLabel lblFailedSection3;
    private javax.swing.JLabel lblFailedSection3Text;
    private javax.swing.JLabel lblFailesSection1Text;
    private javax.swing.JLabel lblFullMarksPass;
    private javax.swing.JLabel lblFullMarksPassText;
    private javax.swing.JLabel lblFullPaperPass;
    private javax.swing.JLabel lblFullPaperPassText;
    private javax.swing.JLabel lblGrades;
    private javax.swing.JLabel lblNumberOfElements;
    private javax.swing.JLabel lblNumberOfElementsText;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPassText;
    private javax.swing.JList<String> listGrades;
    private javax.swing.JTextField txtNewGrade;
    // End of variables declaration//GEN-END:variables
    
    /**
     * get lblBorderLinePass
     * @return
     */
    public JLabel getLblBorderLinePass(){
        if(dMode) System.out.println("View: getLblBorderLinePass()");
        return lblBorderLinePass;
    }

    /**
     * set lblBorderLinePass
     * @param lblBorderLinePass
     */
    public void setLblBorderLinePass(JLabel lblBorderLinePass){
        if(dMode) System.out.println("View: setLblBorderLinePass()");
        this.lblBorderLinePass = lblBorderLinePass;
    }

    /**
     * get lblFail
     * @return
     */
    public JLabel getLblFail(){
        if(dMode) System.out.println("View: getLblFail()");
        return lblFail;
    }

    /**
     * set lblFail
     * @param lblFail
     */
    public void setLblFail(JLabel lblFail){
        if(dMode) System.out.println("View: setLblFail()");
        this.lblFail = lblFail;
    }

    /**
     * get lblPass
     * @return
     */
    public JLabel getLblPass(){
        if(dMode) System.out.println("View: getLblPass()");
        return lblPass;
    }

    /**
     * set lblPass
     * @param lblPass
     */
    public void setLblPass(JLabel lblPass){
        if(dMode) System.out.println("View: setLblPass()");
        this.lblPass = lblPass;
    }

    /**
     * get lblFailedSection
     * @param section
     * @return
     */
    public JLabel getLblFailedSection(int section){
        if(dMode) System.out.println("View: getLblFailedSection(" + section +")");
        return switch (section) {
            case 1 -> lblFailedSection1;
            case 2 -> lblFailedSection2;
            case 3 -> lblFailedSection3;
            default -> lblFailedSection1;
        };
    }

    /**
     * set lblFailedSection
     * @param lblFailedSection
     * @param section
     */
    public void setLblFailedSection(JLabel lblFailedSection,int section){
        if(dMode) System.out.println("View: setLblFailedSection(" + section + ")");
        switch (section) {
            case 1 -> this.lblFailedSection1 = lblFailedSection;
            case 2 -> this.lblFailedSection2 = lblFailedSection;
            case 3 -> this.lblFailedSection3 = lblFailedSection;
            default -> this.lblFailedSection1 = lblFailedSection;
        }
    }

    /**
     * get lblFullMarksPass
     * @return
     */
    public JLabel getLblFullMarksPass(){
        if(dMode) System.out.println("View: getLblFullMarksPass()");
        return lblFullMarksPass;
    }

    /**
     * set lblFullMarksPass
     * @param lblFullMarksPass
     */
    public void setLblFullMarksPass(JLabel lblFullMarksPass){
        if(dMode) System.out.println("View: setLblFullMarksPass()");
        this.lblFullMarksPass = lblFullMarksPass;
    }

    /**
     * get lblFullPaperPass
     * @return
     */
    public JLabel getLblFullPaperPass(){
        if(dMode) System.out.println("View: getLblFullPaperPass()");
        return lblFullPaperPass;
    }

    /**
     * set lblFullPaperPass
     * @param lblFullPaperPass
     */
    public void setLblFullPaperPass(JLabel lblFullPaperPass){
        if(dMode) System.out.println("View: setLblFullPaperPass()");
        this.lblFullPaperPass = lblFullPaperPass;
    }

    /**
     * get lblNumberOfElements
     * @return
     */
    public JLabel getLblNumberOfElements(){
        if(dMode) System.out.println("View: getLblNumberOfElements()");
        return lblNumberOfElements;
    }

    /**
     * set lblNumberOfElements
     * @param lblNumberOfElements
     */
    public void setLblNumberOfElements(JLabel lblNumberOfElements){
        if(dMode) System.out.println("View: setLblNumberOfElements()");
        this.lblNumberOfElements = lblNumberOfElements;
    }

    /**
     * get txtNewGrade
     * @return
     */
    public JTextField getTxtNewGrade(){
        if(dMode) System.out.println("View: getTxtNewGrade()");
        return txtNewGrade;
    }

    /**
     * set txtNewGrade
     * @param txtNewGrade
     */
    public void setTxtNewGrade(JTextField txtNewGrade){
        if(dMode) System.out.println("View: setTxtNewGrade()");
        this.txtNewGrade = txtNewGrade;
    }

    /**
     *get cboxDefaultFile
     * @return
     */
    public JCheckBox getCBoxDefaultFile(){
        if(dMode) System.out.println("View: getCBoxDefaultFile()");
        return cboxDefaultFile;
    }

    /**
     * get listGrades
     * @return
     */
    public JList getListGrades(){
        if(dMode) System.out.println("View: getListGrades()");
        return listGrades;
    }

    /**
     * set listGrades
     * @param listGrades
     */
    public void setListGrades(JList listGrades){
        if(dMode) System.out.println("View: setListGrades()");
        this.listGrades = listGrades;
    }

    /**
     * get btnAddElement
     * @return
     */
    public JButton getBtnAddElement(){
        if(dMode) System.out.println("View: getBtnAddElement()");
        return btnAddElement;
    }

    /**
     * get btnClearAll
     * @return
     */
    public JButton getBtnClearAll(){
        if(dMode) System.out.println("View: getBtnClearAll()");
        return btnClearAll;
    }

    /**
     * get btnDeleteElement
     * @return
     */
    public JButton getBtnDeleteElement(){
        if(dMode) System.out.println("View: getBtnDeleteElement()");
        return btnDeleteElement;
    }

    /**
     *get btnExit
     * @return
     */
    public JButton getBtnExit(){
        if(dMode) System.out.println("View: getBtnExit()");
        return btnExit;
    }

    /**
     * get btnExport
     * @return
     */
    public JButton getBtnExport(){
        if(dMode) System.out.println("View: getBtnExport()");
        return btnExport;
    }

    /**
     * get btnExportReport
     * @return
     */
    public JButton getBtnExportReport(){
        if(dMode) System.out.println("View: getBtnExportReport()");
        return btnExportReport;
    }

    /**
     * get btnImport
     * @return
     */
    public JButton getBtnImport(){
        if(dMode) System.out.println("View: getBtnImport()");
        return btnImport;
    }

    /**
     * set gradesArray
     * @param gradesArray
     */
    public void setGradesArray(DefaultListModel gradesArray){
        if(dMode) System.out.println("View: setGradesArray()");
        this.gradesArray = gradesArray;
    }

    /**
     * get gradesArray
     * @return
     */
    public DefaultListModel getGradesArray(){
        if(dMode) System.out.println("View: getGradesArray()");
        return gradesArray;
    }

    /**
     * get fileChooserTxt
     * @return
     */
    public JFileChooser getFileChooserTxt(){
        if(dMode) System.out.println("View: getFileChooserTxt()");
        return fileChooserTxt;
    }
}
